### ISSUE TITLE
Going back to previous page

### ISSUE THREAD

**Issue by kaneschutzman** [kilianc/mongoose-range-paginate#2]
Are you planning to add and previous page option to this module?

**Comment by kilianc** [comment]
@kaneschutzman in order to create pages you need a different index. You usually achieve that using a map/reduce saved into a view. Since there is no concept of page here but just waling the result set to avoid the cost of `skip`. In order to go to the previous page you need the first record for that page.

If you have a specific case or a proposal I can help with that.
